name: EsLint files on PR - reviewdog

on: 
  push:
    branches: 
      - '**'

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: directory
        run: echo $PWD
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'packages/publisher-dapp'

