name: Eslint check

on:
  pull_request:
    branches: 
      - '**'

jobs:
  eslint_check:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.0.0
      with:
        ghToken: ${{ secrets.REPO_SYNC_TOKEN }}
        eslintFiles: "packages/"
        eslintConfig: "myConfigs/eslint.config.js"
        eslintExt: "js, jsx"
