name: github - repo sync

on:
  schedule:
  - cron:  "*/05 * * * *"
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/singnet/snet-dapp-monorepo.git"
        source_branch: "development"
        destination_branch: "development"
        github_token: ${{ secrets.GITHUB_TOKEN }}
:
     
  repo-sync-publisher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/singnet/snet-dapp-monorepo.git"
        source_branch: "development-publisher"
        destination_branch: "development-publisher"
        github_token: ${{ secrets.GITHUB_TOKEN }}

  repo-sync-staking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/singnet/snet-dapp-monorepo.git"
        source_branch: "development-staking"
        destination_branch: "development-staking"
        github_token: ${{ secrets.GITHUB_TOKEN }}
